language: python

python:
  - "3.4"

services: 
  - mysql

env:
  - DJANGO_VERSION=1.9.6

install:
  - pip install -r requirements.txt

before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - python3 manage.py test
